apiVersion: v1
kind: Service
metadata:
  name: sample-svc
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "10Mbps"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: sample-app
